services:
  - type: web
    name: rag-web-app
    env: python
    runtime: python
    plan: free
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app --timeout 600 --workers 1 --threads 2 --worker-class sync --max-requests 1000 --max-requests-jitter 100 --log-level info"
    healthCheckPath: "/health"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "10000"
